services:
  frontend:
    build:
        context: ./frontend 
        dockerfile: Dockerfile  
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devops_lessons
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
